### ISSUE TITLE
PKCE implementation

### ISSUE THREAD

**Issue by iuioiua** [thorwebdev/everydaylytics#2]
Hi @thorwebdev, 

In the README, you mention that this codebase uses the best method of authentication until PKCE ships, which it now has in `supabase/gotrue` (PR [here](supabase/gotrue#891)). Now, both `@supabase/supabase-js` and `@supabase/auth-helpers-shared` must be updated accordingly.

I'm just placing this issue here once both of those packages are updated for the PKCE implementation. I'm keen to see how the new implementation would improve the current one.

Note: we're using the learnings from this repo to help create [Deno SaaSKit](https://github.com/denoland/saaskit), the next version of the `fresh-saas-toolkit` repo we previously were involved in.

**Comment by thorwebdev** [comment]
@iuioiua we're working on finalising the [`gotrue-js` release](https://github.com/supabase/gotrue-js/pull/591) and then I'll update this to use the PKCE flow, hoping to be able to land this by end of this week 🤞 

FYI, the migration to PKCE flow, should be fairly straighforward:

1. setting of flowType: 'pkce' in `signInWithOAuth`: https://github.com/thorwebdev/everydaylytics/pull/3/files#diff-baa70c3e77c9f54dbf46aa3d4d46ce059b62078aabd17382073a54a3203e48bfR60
2. Exchange the code for a session: https://github.com/thorwebdev/everydaylytics/pull/3/files#diff-baa70c3e77c9f54dbf46aa3d4d46ce059b62078aabd17382073a54a3203e48bfR19

I'll keep this issue open until then, thanks.

**Comment by iuioiua** [comment]
Great to hear, and good to see we will no longer have to rely on the `AuthFragmentCatcher` island.

**Comment by thorwebdev** [comment]
@iuioiua quick note that the implementation approach has slightly changed:

1. Implement the `CookieAuthStorageAdapter`: https://github.com/thorwebdev/everydaylytics/pull/4/files#diff-d46353c8af17bdfb79c2fe38075b48e2609c338f1e9a297c25ed1078875690eaR11
2. Handle the auth code exchange: https://github.com/thorwebdev/everydaylytics/pull/4/files#diff-baa70c3e77c9f54dbf46aa3d4d46ce059b62078aabd17382073a54a3203e48bfR14
3. Redirect `signInWithOauth` to api route: https://github.com/thorwebdev/everydaylytics/pull/4/files#diff-baa70c3e77c9f54dbf46aa3d4d46ce059b62078aabd17382073a54a3203e48bfR80

Also note that PKCE is not yet fully rolled out to all hosted supabase projects. Let me know if you want me to enable it for your testing projects (just send me your project ref).

I'll keep this issue open until PKCE is fully rolled out, thanks.

**Comment by iuioiua** [comment]
This progress is cool to see! Yeah, it'd be good to start testing this out on Deno SaaSKit. The project ID is `nukuxwqzfcatxzheitpv`.

**Comment by thorwebdev** [comment]
@iuioiua your project has been enabled for PKCE, you're good to go 👍

**Comment by iuioiua** [comment]
Thank you, @thorwebdev. We can play around with this idea but might only deploy once out of beta 😊✈️🎉
